### ISSUE TITLE
Add comment section in Blogs

### ISSUE THREAD

**Issue by imSrbh** [1pani/1pani.github.io#3]

**Comment by 1pani** [comment]
Thanks @imSrbh for pointing out this.
This feature has been added and can be viewed [here](https://github.com/1pani/1pani.github.io/commit/dbf77674ffe671ef2d750ba377ac5feca0249a08)

Hence, I am closing this issue.

**Comment by imSrbh** [comment]
@1pani  Now It Looks great.
